In [6]:
import pandas as pd

In [2]:
pip install alpha_vantage pandas

Requirement already satisfied: alpha_vantage in c:\users\nitec\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: pandas in c:\users\nitec\anaconda3\lib\site-packages (0.25.1)
Requirement already satisfied: requests in c:\users\nitec\anaconda3\lib\site-packages (from alpha_vantage) (2.22.0)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\nitec\anaconda3\lib\site-packages (from pandas) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\nitec\anaconda3\lib\site-packages (from pandas) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in c:\users\nitec\anaconda3\lib\site-packages (from pandas) (1.16.5)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\nitec\anaconda3\lib\site-packages (from requests->alpha_vantage) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\nitec\anaconda3\lib\site-packages (from requests->alpha_vantage) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\nitec\anaconda3\lib\site-packages (from requests->alpha_vantage) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nitec\anaconda3\lib\site-packages (from requests->alpha_vantage) (2019.9.11)
Requirement already satisfied: six>=1.5 in c:\users\nitec\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key='A0DF51WHUDBQ8UOH')
# Get json object with the get_daily data and another with  the call's metadata
data, meta_data = ts.get_daily('GOOGL')
data_frame = pd.DataFrame(data)

{'2020-03-20': {'1. open': '1130.9000',
  '2. high': '1138.4800',
  '3. low': '1062.1000',
  '4. close': '1068.2100',
  '5. volume': '4088847'},
 '2020-03-19': {'1. open': '1088.2200',
  '2. high': '1152.6100',
  '3. low': '1055.5500',
  '4. close': '1111.6700',
  '5. volume': '3703248'},
 '2020-03-18': {'1. open': '1059.9400',
  '2. high': '1104.9900',
  '3. low': '1037.0000',
  '4. close': '1091.1900',
  '5. volume': '4636840'},
 '2020-03-17': {'1. open': '1090.6400',
  '2. high': '1126.0000',
  '3. low': '1049.1000',
  '4. close': '1118.0600',
  '5. volume': '4159686'},
 '2020-03-16': {'1. open': '1089.6100',
  '2. high': '1145.4700',
  '3. low': '1067.0800',
  '4. close': '1073.0000',
  '5. volume': '4825981'},
 '2020-03-13': {'1. open': '1174.9900',
  '2. high': '1214.4000',
  '3. low': '1112.2900',
  '4. close': '1214.2700',
  '5. volume': '3969973'},
 '2020-03-12': {'1. open': '1122.6200',
  '2. high': '1188.7500',
  '3. low': '1108.4700',
  '4. close': '1111.5500',
  '5. volume': '4716293'},
 '2020-03-11': {'1. open': '1248.2700',
  '2. high': '1256.9300',
  '3. low': '1191.1400',
  '4. close': '1210.9000',
  '5. volume': '2741694'},
 '2020-03-10': {'1. open': '1254.3900',
  '2. high': '1275.8500',
  '3. low': '1214.5100',
  '4. close': '1275.1700',
  '5. volume': '2743566'},
 '2020-03-09': {'1. open': '1204.9600',
  '2. high': '1252.7300',
  '3. low': '1198.0400',
  '4. close': '1215.7900',
  '5. volume': '3462578'},
 '2020-03-06': {'1. open': '1269.9500',
  '2. high': '1302.7500',
  '3. low': '1257.2100',
  '4. close': '1295.7400',
  '5. volume': '3232315'},
 '2020-03-05': {'1. open': '1345.5500',
  '2. high': '1353.6300',
  '3. low': '1301.6400',
  '4. close': '1314.7600',
  '5. volume': '2718982'},
 '2020-03-04': {'1. open': '1358.9600',
  '2. high': '1382.7800',
  '3. low': '1337.0000',
  '4. close': '1381.6000',
  '5. volume': '2379856'},
 '2020-03-03': {'1. open': '1397.6800',
  '2. high': '1408.1900',
  '3. low': '1329.2400',
  '4. close': '1337.7200',
  '5. volume': '2830112'},
 '2020-03-02': {'1. open': '1351.3900',
  '2. high': '1387.4700',
  '3. low': '1325.2000',
  '4. close': '1386.3200',
  '5. volume': '2771463'},
 '2020-02-28': {'1. open': '1274.3100',
  '2. high': '1342.4500',
  '3. low': '1268.2100',
  '4. close': '1339.2500',
  '5. volume': '4010900'},
 '2020-02-27': {'1. open': '1359.1400',
  '2. high': '1369.4000',
  '3. low': '1314.2400',
  '4. close': '1314.9500',
  '5. volume': '3114476'},
 '2020-02-26': {'1. open': '1394.9800',
  '2. high': '1413.6700',
  '3. low': '1376.5500',
  '4. close': '1390.4700',
  '5. volume': '2490178'},
 '2020-02-25': {'1. open': '1431.0000',
  '2. high': '1436.8500',
  '3. low': '1380.4200',
  '4. close': '1386.3200',
  '5. volume': '2578966'},
 '2020-02-24': {'1. open': '1423.0500',
  '2. high': '1436.3800',
  '3. low': '1406.7900',
  '4. close': '1419.8600',
  '5. volume': '2478039'},
 '2020-02-21': {'1. open': '1504.5800',
  '2. high': '1510.9400',
  '3. low': '1478.4900',
  '4. close': '1483.4600',
  '5. volume': '2126843'},
 '2020-02-20': {'1. open': '1519.0100',
  '2. high': '1527.0700',
  '3. low': '1504.2600',
  '4. close': '1516.9900',
  '5. volume': '1298386'},
 '2020-02-19': {'1. open': '1527.2000',
  '2. high': '1530.7400',
  '3. low': '1520.9800',
  '4. close': '1524.8700',
  '5. volume': '1137338'},
 '2020-02-18': {'1. open': '1514.3400',
  '2. high': '1530.5600',
  '3. low': '1511.0100',
  '4. close': '1519.4400',
  '5. volume': '1284011'},
 '2020-02-14': {'1. open': '1514.5300',
  '2. high': '1520.0500',
  '3. low': '1505.5500',
  '4. close': '1518.7300',
  '5. volume': '1159857'},
 '2020-02-13': {'1. open': '1510.0000',
  '2. high': '1525.9500',
  '3. low': '1504.0000',
  '4. close': '1513.3900',
  '5. volume': '1145658'},
 '2020-02-12': {'1. open': '1515.8600',
  '2. high': '1520.3000',
  '3. low': '1508.6700',
  '4. close': '1518.6300',
  '5. volume': '1552136'},
 '2020-02-11': {'1. open': '1513.2700',
  '2. high': '1529.8800',
  '3. low': '1505.4500',
  '4. close': '1510.0600',
  '5. volume': '1742647'},
 '2020-02-10': {'1. open': '1477.2300',
  '2. high': '1508.8800',
  '3. low': '1475.2000',
  '4. close': '1508.6600',
  '5. volume': '1915072'},
 '2020-02-07': {'1. open': '1467.3800',
  '2. high': '1485.2400',
  '3. low': '1465.4100',
  '4. close': '1479.1100',
  '5. volume': '1418049'},
 '2020-02-06': {'1. open': '1451.9800',
  '2. high': '1481.5600',
  '3. low': '1450.4800',
  '4. close': '1475.9700',
  '5. volume': '1891079'},
 '2020-02-05': {'1. open': '1463.6100',
  '2. high': '1464.5800',
  '3. low': '1429.6700',
  '4. close': '1446.0500',
  '5. volume': '1818793'},
 '2020-02-04': {'1. open': '1454.4900',
  '2. high': '1467.3400',
  '3. low': '1422.0300',
  '4. close': '1445.4100',
  '5. volume': '4793967'},
 '2020-02-03': {'1. open': '1461.6500',
  '2. high': '1486.3000',
  '3. low': '1456.6100',
  '4. close': '1482.6000',
  '5. volume': '3608760'},
 '2020-01-31': {'1. open': '1467.8600',
  '2. high': '1469.6700',
  '3. low': '1427.0600',
  '4. close': '1432.7800',
  '5. volume': '2191075'},
 '2020-01-30': {'1. open': '1438.1000',
  '2. high': '1455.2500',
  '3. low': '1435.0000',
  '4. close': '1454.2500',
  '5. volume': '1355472'},
 '2020-01-29': {'1. open': '1458.4600',
  '2. high': '1464.1400',
  '3. low': '1445.3800',
  '4. close': '1456.7000',
  '5. volume': '1081964'},
 '2020-01-28': {'1. open': '1441.7400',
  '2. high': '1454.8000',
  '3. low': '1430.3600',
  '4. close': '1450.5000',
  '5. volume': '1486586'},
 '2020-01-27': {'1. open': '1431.5400',
  '2. high': '1436.5800',
  '3. low': '1419.5000',
  '4. close': '1431.7300',
  '5. volume': '1706566'},
 '2020-01-24': {'1. open': '1492.8200',
  '2. high': '1494.2000',
  '3. low': '1463.1800',
  '4. close': '1466.1700',
  '5. volume': '1489280'},
 '2020-01-23': {'1. open': '1487.5500',
  '2. high': '1493.5000',
  '3. low': '1480.3200',
  '4. close': '1484.6900',
  '5. volume': '1332562'},
 '2020-01-22': {'1. open': '1489.7300',
  '2. high': '1500.5800',
  '3. low': '1482.6600',
  '4. close': '1484.1700',
  '5. volume': '1422946'},
 '2020-01-21': {'1. open': '1479.0000',
  '2. high': '1489.8800',
  '3. low': '1470.2100',
  '4. close': '1482.2500',
  '5. volume': '2387178'},
 '2020-01-17': {'1. open': '1462.5400',
  '2. high': '1480.5500',
  '3. low': '1456.5500',
  '4. close': '1479.5200',
  '5. volume': '2621175'},
 '2020-01-16': {'1. open': '1445.4500',
  '2. high': '1450.7000',
  '3. low': '1440.0000',
  '4. close': '1450.1600',
  '5. volume': '1304040'},
 '2020-01-15': {'1. open': '1433.0200',
  '2. high': '1440.7800',
  '3. low': '1431.6600',
  '4. close': '1439.2000',
  '5. volume': '1077519'},
 '2020-01-14': {'1. open': '1440.0000',
  '2. high': '1442.6300',
  '3. low': '1427.7700',
  '4. close': '1430.5900',
  '5. volume': '1305636'},
 '2020-01-13': {'1. open': '1435.2500',
  '2. high': '1441.4800',
  '3. low': '1425.3700',
  '4. close': '1440.0300',
  '5. volume': '1525568'},
 '2020-01-10': {'1. open': '1429.4700',
  '2. high': '1434.9400',
  '3. low': '1419.6000',
  '4. close': '1428.9600',
  '5. volume': '1313178'},
 '2020-01-09': {'1. open': '1421.9300',
  '2. high': '1428.6800',
  '3. low': '1410.2100',
  '4. close': '1419.7900',
  '5. volume': '1661438'},
 '2020-01-08': {'1. open': '1394.8200',
  '2. high': '1411.8500',
  '3. low': '1392.6300',
  '4. close': '1405.0400',
  '5. volume': '1766274'},
 '2020-01-07': {'1. open': '1400.4600',
  '2. high': '1403.5000',
  '3. low': '1391.5600',
  '4. close': '1395.1100',
  '5. volume': '1726456'},
 '2020-01-06': {'1. open': '1351.6300',
  '2. high': '1398.3200',
  '3. low': '1351.0000',
  '4. close': '1397.8100',
  '5. volume': '2339343'},
 '2020-01-03': {'1. open': '1348.0000',
  '2. high': '1373.7500',
  '3. low': '1347.3200',
  '4. close': '1361.5200',
  '5. volume': '1170629'},
 '2020-01-02': {'1. open': '1348.4100',
  '2. high': '1368.6800',
  '3. low': '1346.4900',
  '4. close': '1368.6800',
  '5. volume': '1364265'},
 '2019-12-31': {'1. open': '1335.7900',
  '2. high': '1340.6600',
  '3. low': '1332.1300',
  '4. close': '1339.3900',
  '5. volume': '976061'},
 '2019-12-30': {'1. open': '1356.8100',
  '2. high': '1357.0000',
  '3. low': '1337.8400',
  '4. close': '1339.7100',
  '5. volume': '1000592'},
 '2019-12-27': {'1. open': '1364.0000',
  '2. high': '1367.0700',
  '3. low': '1353.0000',
  '4. close': '1354.6400',
  '5. volume': '1160873'},
 '2019-12-26': {'1. open': '1346.5500',
  '2. high': '1363.2000',
  '3. low': '1345.5100',
  '4. close': '1362.4700',
  '5. volume': '1183800'},
 '2019-12-24': {'1. open': '1350.2100',
  '2. high': '1352.0100',
  '3. low': '1344.1600',
  '4. close': '1344.4300',
  '5. volume': '673410'},
 '2019-12-23': {'1. open': '1358.7300',
  '2. high': '1361.8500',
  '3. low': '1348.0000',
  '4. close': '1350.6300',
  '5. volume': '996967'},
 '2019-12-20': {'1. open': '1363.1000',
  '2. high': '1364.0000',
  '3. low': '1350.7300',
  '4. close': '1351.2200',
  '5. volume': '2513849'},
 '2019-12-19': {'1. open': '1351.9100',
  '2. high': '1357.5300',
  '3. low': '1348.7500',
  '4. close': '1356.4400',
  '5. volume': '1521082'},
 '2019-12-18': {'1. open': '1357.0000',
  '2. high': '1359.4300',
  '3. low': '1350.4600',
  '4. close': '1351.9100',
  '5. volume': '1166733'},
 '2019-12-17': {'1. open': '1362.4100',
  '2. high': '1364.3300',
  '3. low': '1350.7700',
  '4. close': '1354.8900',
  '5. volume': '1648549'},
 '2019-12-16': {'1. open': '1355.0000',
  '2. high': '1363.5300',
  '3. low': '1350.6100',
  '4. close': '1360.7000',
  '5. volume': '1406457'},
 '2019-12-13': {'1. open': '1347.9000',
  '2. high': '1351.3500',
  '3. low': '1341.6600',
  '4. close': '1346.8700',
  '5. volume': '1658684'},
 '2019-12-12': {'1. open': '1343.2100',
  '2. high': '1354.5800',
  '3. low': '1338.2000',
  '4. close': '1348.4900',
  '5. volume': '1456466'},
 '2019-12-11': {'1. open': '1348.3000',
  '2. high': '1349.8900',
  '3. low': '1341.1000',
  '4. close': '1344.2500',
  '5. volume': '1024308'},
 '2019-12-10': {'1. open': '1339.9400',
  '2. high': '1348.0000',
  '3. low': '1334.0000',
  '4. close': '1342.8900',
  '5. volume': '880430'},
 '2019-12-09': {'1. open': '1338.8600',
  '2. high': '1357.5500',
  '3. low': '1336.0700',
  '4. close': '1342.9900',
  '5. volume': '1556889'},
 '2019-12-06': {'1. open': '1332.7500',
  '2. high': '1342.4700',
  '3. low': '1331.2300',
  '4. close': '1339.3900',
  '5. volume': '1648729'},
 '2019-12-05': {'1. open': '1327.0000',
  '2. high': '1327.9800',
  '3. low': '1314.3200',
  '4. close': '1326.9600',
  '5. volume': '1220631'},
 '2019-12-04': {'1. open': '1306.1000',
  '2. high': '1324.2700',
  '3. low': '1303.0500',
  '4. close': '1318.9400',
  '5. volume': '1776392'},
 '2019-12-03': {'1. open': '1278.6600',
  '2. high': '1297.2300',
  '3. low': '1277.0500',
  '4. close': '1294.7400',
  '5. volume': '1480026'},
 '2019-12-02': {'1. open': '1302.5600',
  '2. high': '1305.4400',
  '3. low': '1280.3800',
  '4. close': '1288.8600',
  '5. volume': '1328889'},
 '2019-11-29': {'1. open': '1306.6000',
  '2. high': '1309.9500',
  '3. low': '1303.2300',
  '4. close': '1304.0900',
  '5. volume': '640069'},
 '2019-11-27': {'1. open': '1315.4200',
  '2. high': '1317.6400',
  '3. low': '1309.4700',
  '4. close': '1312.1300',
  '5. volume': '940536'},
 '2019-11-26': {'1. open': '1309.9100',
  '2. high': '1314.0100',
  '3. low': '1304.0400',
  '4. close': '1313.0000',
  '5. volume': '1097089'},
 '2019-11-25': {'1. open': '1296.2600',
  '2. high': '1310.4100',
  '3. low': '1295.6100',
  '4. close': '1305.6400',
  '5. volume': '1179658'},
 '2019-11-22': {'1. open': '1303.0000',
  '2. high': '1306.9000',
  '3. low': '1289.3600',
  '4. close': '1293.6700',
  '5. volume': '1388912'},
 '2019-11-21': {'1. open': '1299.2500',
  '2. high': '1311.1200',
  '3. low': '1290.7500',
  '4. close': '1300.1400',
  '5. volume': '1277338'},
 '2019-11-20': {'1. open': '1311.3600',
  '2. high': '1313.2100',
  '3. low': '1289.2100',
  '4. close': '1301.8600',
  '5. volume': '1445870'},
 '2019-11-19': {'1. open': '1326.6300',
  '2. high': '1326.6300',
  '3. low': '1311.7700',
  '4. close': '1312.5900',
  '5. volume': '1093629'},
 '2019-11-18': {'1. open': '1332.3400',
  '2. high': '1333.9200',
  '3. low': '1316.1600',
  '4. close': '1319.8400',
  '5. volume': '1399374'},
 '2019-11-15': {'1. open': '1315.0500',
  '2. high': '1333.5400',
  '3. low': '1311.8900',
  '4. close': '1333.5400',
  '5. volume': '1964955'},
 '2019-11-14': {'1. open': '1295.0000',
  '2. high': '1315.7200',
  '3. low': '1293.9400',
  '4. close': '1309.1500',
  '5. volume': '1450039'},
 '2019-11-13': {'1. open': '1293.1800',
  '2. high': '1302.5200',
  '3. low': '1292.1500',
  '4. close': '1296.1800',
  '5. volume': '936085'},
 '2019-11-12': {'1. open': '1298.5700',
  '2. high': '1309.3500',
  '3. low': '1294.2400',
  '4. close': '1297.2100',
  '5. volume': '1444342'},
 '2019-11-11': {'1. open': '1304.0000',
  '2. high': '1304.9000',
  '3. low': '1295.8700',
  '4. close': '1298.2800',
  '5. volume': '861860'},
 '2019-11-08': {'1. open': '1301.5200',
  '2. high': '1317.1100',
  '3. low': '1301.5200',
  '4. close': '1309.0000',
  '5. volume': '1521892'},
 '2019-11-07': {'1. open': '1294.2800',
  '2. high': '1322.6500',
  '3. low': '1293.7500',
  '4. close': '1306.9400',
  '5. volume': '2257005'},
 '2019-11-06': {'1. open': '1290.0900',
  '2. high': '1292.9900',
  '3. low': '1282.2700',
  '4. close': '1291.0100',
  '5. volume': '1231265'},
 '2019-11-05': {'1. open': '1291.2000',
  '2. high': '1297.2400',
  '3. low': '1289.3800',
  '4. close': '1291.4400',
  '5. volume': '1257427'},
 '2019-11-04': {'1. open': '1276.1100',
  '2. high': '1292.5000',
  '3. low': '1276.1100',
  '4. close': '1289.6100',
  '5. volume': '1531622'},
 '2019-11-01': {'1. open': '1265.8000',
  '2. high': '1273.0000',
  '3. low': '1259.7100',
  '4. close': '1272.2500',
  '5. volume': '1440607'},
 '2019-10-31': {'1. open': '1260.0000',
  '2. high': '1266.5200',
  '3. low': '1249.4800',
  '4. close': '1258.8000',
  '5. volume': '1595154'},
 '2019-10-30': {'1. open': '1255.1500',
  '2. high': '1268.0200',
  '3. low': '1250.6500',
  '4. close': '1260.7000',
  '5. volume': '1460193'},
 '2019-10-29': {'1. open': '1276.0000',
  '2. high': '1280.8000',
  '3. low': '1255.6100',
  '4. close': '1260.6600',
  '5. volume': '2632715'},
 '2019-10-28': {'1. open': '1275.0000',
  '2. high': '1299.2400',
  '3. low': '1272.3100',
  '4. close': '1288.9800',
  '5. volume': '3010505'}}

In [8]:
data_frame = pd.DataFrame(data)
data_frame

,2020-03-20,2020-03-19,2020-03-18,2020-03-17,2020-03-16,2020-03-13,2020-03-12,2020-03-11,2020-03-10,2020-03-09,...,2019-11-08,2019-11-07,2019-11-06,2019-11-05,2019-11-04,2019-11-01,2019-10-31,2019-10-30,2019-10-29,2019-10-28
1. open,1130.9000,1088.2200,1059.9400,1090.6400,1089.6100,1174.9900,1122.6200,1248.2700,1254.3900,1204.9600,...,1301.5200,1294.2800,1290.0900,1291.2000,1276.1100,1265.8000,1260.0000,1255.1500,1276.0000,1275.0000
2. high,1138.4800,1152.6100,1104.9900,1126.0000,1145.4700,1214.4000,1188.7500,1256.9300,1275.8500,1252.7300,...,1317.1100,1322.6500,1292.9900,1297.2400,1292.5000,1273.0000,1266.5200,1268.0200,1280.8000,1299.2400
3. low,1062.1000,1055.5500,1037.0000,1049.1000,1067.0800,1112.2900,1108.4700,1191.1400,1214.5100,1198.0400,...,1301.5200,1293.7500,1282.2700,1289.3800,1276.1100,1259.7100,1249.4800,1250.6500,1255.6100,1272.3100
4. close,1068.2100,1111.6700,1091.1900,1118.0600,1073.0000,1214.2700,1111.5500,1210.9000,1275.1700,1215.7900,...,1309.0000,1306.9400,1291.0100,1291.4400,1289.6100,1272.2500,1258.8000,1260.7000,1260.6600,1288.9800
5. volume,4088847,3703248,4636840,4159686,4825981,3969973,4716293,2741694,2743566,3462578,...,1521892,2257005,1231265,1257427,1531622,1440607,1595154,1460193,2632715,3010505